export const styles = {
  drawerPaper: {
    width: { xs: "100%", sm: 420 },
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    height: "100%",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    p: 2,
    borderBottom: "1px solid #e0e0e0",
    backgroundColor: "#fafafa",
  },
  orderTimerBanner: {
    p: 1.5,
    mb: 2,
    backgroundColor: "#f0f7ff",
    border: "1px solid #cce3fd",
    borderRadius: 2,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 1,
  },
  caption: {
    fontWeight: 700,
    color: "primary.main",
    display: "block",
    lineHeight: 1.2,
  },
  content: {
    flex: 1,
    overflowY: "auto",
    p: 2,
  },
  emptyBox: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    textAlign: "center",
    color: "text.secondary",
    p: 3,
  },
  itemCard: {
    display: "flex",
    alignItems: "flex-start",
    p: 1.5,
    mb: 2,
    borderRadius: 2,
    border: "1px solid #eeeeee",
    position: "relative",
    backgroundColor: "#ffffff",
    boxShadow: "0 1px 3px rgba(0,0,0,0.05)",
  },
  itemThumbnail: (bgColor?: string) => ({
    width: 60,
    height: 60,
    borderRadius: 2,
    backgroundColor: bgColor || "#e3f2fd",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 28,
    mr: 2,
    flexShrink: 0,
  }),
  itemInfo: {
    flexGrow: 1,
  },
  footer: {
    borderTop: "1px solid #e0e0e0",
    p: 2.5,
    backgroundColor: "#ffffff",
    boxShadow: "0 -2px 8px rgba(0,0,0,0.05)",
  },
  summaryRow: {
    display: "flex",
    justifyContent: "space-between",
    mb: 1,
  },
  actions: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    mt: 1.2,
    gap: 1,
  },
  productTotal: {
    display: "flex",
    alignItems: "center",
    gap: 0.5,
  },
};
